FROM oven/bun:1.2

WORKDIR /app

COPY package.json ./
COPY bun.lock ./
COPY src ./src

RUN bun install

COPY . .

RUN apt-get update -y && apt-get install -y openssl

EXPOSE 3000

CMD ["bun", "run", "dev"]